### ISSUE TITLE
project scope?

### ISSUE THREAD

**Issue by 7yl4r** [oceanmodeling/searvey#129]
Looking at the README it is not clear the scope of this project. It appears very ambitious in that it aims to provide a "Unified catalogue of observational data" - which certainly too big of a task. Looking deeper into the docs it appears that the focus here is on bouy data, or perhaps in situ water data? A revision to the introductory docs would help clarify for newcomers to this repo.

**Comment by brey** [comment]
Hi @Tyral, indeed the current implementation is focused on in situ water data because these are our current needs. However the perspective is open-ended. We can, in principle, expose all the data that the provider has. 

However, it would need some form of standardisation before this can happen. We already have problems with the sea level height available in the same location from different sensors/providers and how that should be handled. It also depends on the features available from the provider's API. 

We are exploring what are the best way to unify the user experience through a consistent and uniform API. 

Future developments on additional sources would depend on user's needs and participation in the development. The general comment there reflects our attitude to consider any kind of data that relates to ocean modelling and explore how they can be integrated into `searvey`.

Needless to say, this is a work in progress.
