### ISSUE TITLE
active status for COOPS stations

### ISSUE THREAD

**Issue by carolakaiser** [oceanmodeling/searvey#45]
When filtering the COOPS stations for being active like this:

coops_active = stations_coops[stations_coops['is_active']]   # comes back as True/False

there are some results that show a station as active but those stations do either not exist on the https://tidesandcurrents.noaa.gov website or deliver a "No data was found" result.

What API do you use to get the active status (is it the NOAA OpenDap server or anything like that?)

Examples: 
https://tidesandcurrents.noaa.gov/waterlevels.html?id=8632837
https://tidesandcurrents.noaa.gov/waterlevels.html?id=8574728

**Comment by pmav99** [comment]
Hi Carola, 

the COOPS API was developed by @zacharyburnett when he was still working for NOAA. I can't say that I am intimately familiar with COOPS. My understanding is that the station metadata are parsed from these HTML tables: 

- https://access.co-ops.nos.noaa.gov/nwsproducts.html?type=current#current
- https://access.co-ops.nos.noaa.gov/nwsproducts.html?type=current#hist

AFAIK the stations that are referenced in the first table are marked as active. In any case the pandas DataFrame that gets returned by the COOPS function contains a column named `status` which is what we use in order to figure out the value of the `is_active` column.

I don't think that COOPS provide a timestamp, so we can't infer the value in the same way we do for IOC.

**Comment by zacharyburnett** [comment]
@pmav99 is correct, currently the module uses those pages to determine active status. I was not aware that some "active" stations don't actually have data; I can look into adding querying of the data to the status checker.

**Comment by pmav99** [comment]
I guess, this has been resolved. If not feel free to reopen and provide additional information. 
Closing
