### ISSUE TITLE
USGS stations filter by region

### ISSUE THREAD

**Issue by carolakaiser** [oceanmodeling/searvey#88]
Hey All,

I have a shapefile that I would like to use to filter the USGS stations by region. 
The shapefile can be downloaded here: https://tinyurl.com/4h6evhfk

I convert the shapefile to a geopandas framework. This is read in successfully (I can see a matplotlib plot). However the retrieval for the USGS stations for this region fails. Could you please help?

My code is this (please note, this is a Python environment under Windows):
[CERA_test.py.zip](https://github.com/oceanmodeling/searvey/files/11580628/CERA_test.py.zip)

**Comment by SorooshMani-NOAA** [comment]
@carolakaiser sorry I missed this issue! Let me take a look and get back to you

**Comment by SorooshMani-NOAA** [comment]
@carolakaiser the issue seems to be the object type you're passing to the `get_usgs_stations` for the region. The region object needs to be of `shapely.Polygon` or `shapely.MultiPolygon` type. In the attached script a `geopandas.GeoDataFrame` is being passed. To get a `shapely` geometry object from it, you'd need to get its "unioned" geometry property by calling `df.unary_union`:

```diff
  df = gpd.read_file('/home/smani/downloads/CERA_shptest/CERA_shptest.shp')
  # fetch all USGS stations and filter by region
- usgs_stations = usgs.get_usgs_stations(region=df)
+ usgs_stations = usgs.get_usgs_stations(region=df.unary_union)

```

**Comment by carolakaiser** [comment]
@SorooshMani-NOAA Thank you very much. This works!

**Comment by SorooshMani-NOAA** [comment]
OK, great! I'll close the ticket for now, if you still notice any issues related to this filtering please feel free to reopen it.
